### ISSUE TITLE
Tab bar covers bottom of page contents sometimes

### ISSUE THREAD

**Issue by euniceyoh** [DFG-SAPSE/SEMS#8]
**Example of issue:** 
on booking confirmation, you can scroll down to see "cancel meeting" but it doesn't persist

**Current fix:** 
About the fact that the Tab bar blocked the bottom of the page, I added a quick fix by adding another layer of ScrollView as a wrapper for each component in booking. Not sure if it's the most sustainable one, but it does the trick for now. We can easily revert it in the future. It's a small issue so we shouldn't spend too much time on it, I would suggest. (source: https://github.com/DFG-SAPSE/SEMS/pull/6)

**Solution:** 
Create a sustainable fix

**Comment by quanphan2906** [comment]
I would close this issue due it is trivial. We should be grouped with a bigger frontend revamp/review project
